### ISSUE TITLE
Liquid placeholders make `cargo` and `rust-analyzer` fail

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_new#10]
For example, `"{{project-name}}"` in `Cargo.toml` is not a valid crate name, so the template itself cannot be compiled. This makes it harder for maintainers of the template to make changes.

Generated repos are not affected by this issue, only the template itself.

**Comment by benfrankel** [comment]
Okay I found an approach that works:

1. Split `Cargo.toml` into a `Cargo.toml.template` (or w/e) with Liquid placeholders, and a `Cargo.toml` with valid syntax.
2. Add `"Cargo.toml.template"` to the `include` list in `cargo-generate.toml` (this can be `"*.template"` so it only has to be added once).
3. Add `file::rename("Cargo.toml.template", "Cargo.toml");` to the post-generate hook.

**Comment by bas-ie** [comment]
Oh, funny I was just strongly considering using `sed` in a pre-commit lol... nice one.

**Comment by benfrankel** [comment]
This does mean that there will be 2 copies of each templated file that should be kept in sync, but that's a sacrifice I was prepared to make for a working solution anyways. Better than 2 branches of the entire repo :P

**Comment by janhohenheim** [comment]
@BD103 if you feel like doing some CI magic at some point, we could issue a warning if a PR touches only one file when there exist both `foo.rs` and `foo.rs.template` 👀
